### ISSUE TITLE
What kinda questions do we want?

### ISSUE THREAD

**Issue by suhavni** [GigaCatZ/Frontend#1]
[
![image](https://user-images.githubusercontent.com/66020871/132079228-22c0ae6d-0c9b-4992-b589-076ff143a32a.png)
](url)

![image](https://user-images.githubusercontent.com/66020871/132079308-0c11cbbc-7799-4752-be76-1a95a6278295.png)

**Comment by vnssr** [comment]
changed the char limit for title to 120 and no limit for body
