### ISSUE TITLE
Something to be added (maybe in patch 2.0 or whenever available)

### ISSUE THREAD

**Issue by suhavni** [GigaCatZ/Frontend#3]
Could tags be linked to the search page of the respective tags? that would be so cool!

(like when we press on it in homepage / in thread/[id] page
Like pressing on these:
![image](https://user-images.githubusercontent.com/66020871/132079536-5c1782b5-9381-4091-8eb7-4f0b94f367de.png)
![image](https://user-images.githubusercontent.com/66020871/132079496-09adb67a-f979-4ef2-a3b9-af2e50ee3ad3.png)
![image](https://user-images.githubusercontent.com/66020871/132079510-d752dcc4-4e2e-4e9e-8e4e-676a36048e10.png)

Leads to this:
![image](https://user-images.githubusercontent.com/66020871/132079526-2cf7be7e-95be-4f40-b2df-8c0b200b3031.png)

**Comment by vnssr** [comment]
done!
